# Generated by Django 5.2.12 on 2026-04-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLUB_ADMIN', 'Club Admin'), ('MEMBER', 'Member'), ('STUDENT', 'Student')], default='MEMBER', max_length=10),
        ),
    ]
