# Generated by Django 5.2.12 on 2026-04-21 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_make_donor_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
